## SPRINT 3 – ADVANCED STATISTICS & FEATURE ENGINEERING

In [30]:
import pandas as pd
import warnings 
warnings.filterwarnings("ignore")

In [31]:
df = pd.read_csv("Cleaned_Data.csv")
df

,Title,Rating,Number_of_reviews,bought_in_last_month,Current/discounted_price,Price_on_variant,Listed_price,is_best_seller,is_sponsored,is_couponed,buy_box_availability,delivery_details,sustainability_badges,image_url,collected_at
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6,375.0,300.0,89.68,basic variant price: 2.4GHz,159.00,No Badge,Sponsored,Save 15% with coupon,Add to cart,"Delivery Mon, Sep 1",Carbon impact,https://m.media-amazon.com/images/I/71pAqiVEs3...,2025-08-21 11:14:00
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3,115.0,6000.0,9.99,basic variant price: nan,15.99,No Badge,Sponsored,No Coupon,Add to cart,"Delivery Fri, Aug 29",No Badge,https://m.media-amazon.com/images/I/61nbF6aVIP...,2025-08-21 11:14:00
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6,115.0,2000.0,314.00,basic variant price: nan,349.00,No Badge,Sponsored,No Coupon,Add to cart,"Delivery Mon, Sep 1",No Badge,https://m.media-amazon.com/images/I/61h78MEXoj...,2025-08-21 11:14:00
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6,115.0,10000.0,74.99,basic variant price: $162.24,66.00,Best Seller,Organic,No Coupon,Add to cart,Not Available,No Badge,https://m.media-amazon.com/images/I/61SUj2aKoE...,2025-08-21 11:14:00
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8,115.0,10000.0,74.99,basic variant price: $72.74,66.00,No Badge,Organic,No Coupon,Add to cart,Not Available,No Badge,https://m.media-amazon.com/images/I/61bMNCeAUA...,2025-08-21 11:14:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24273,"Elgato 4K Pro, Internal Capture Card: 8K60 Pas...",5.0,1.0,100.0,195.99,basic variant price: nan,66.00,No Badge,Organic,No Coupon,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery Tu...",No Badge,https://m.media-amazon.com/images/I/51KCB+egEs...,2025-08-30 19:56:00
24274,"Arlo Essential Spotlight Camera, Wireless Secu...",4.2,20.0,200.0,89.99,basic variant price: $25.00 off coupon applied,66.00,No Badge,Organic,Save $25.00 with coupon,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery Mo...",No Badge,https://m.media-amazon.com/images/I/51jV+o1LZE...,2025-08-30 19:56:00
24275,"GIGABYTE - AORUS FO32U2-32"" QD OLED Gaming Mon...",4.3,57.0,50.0,899.99,basic variant price: Lowest price in 30 days,1099.99,Save 18%,Organic,No Coupon,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery We...",No Badge,https://m.media-amazon.com/images/I/71ySPkNLkG...,2025-08-30 19:56:00
24276,Monoprice XLR Male to 1/4-Inch TRS Male Cable ...,4.7,115.0,500.0,10.39,basic variant price: nan,15.98,No Badge,Organic,No Coupon,Add to cart,"FREE delivery Thu, Sep 4 on $35 of items shipp...",No Badge,https://m.media-amazon.com/images/I/411c0JFJ79...,2025-08-30 19:56:00
24277,Lorex Fusion 1080p HD Security Camera System w...,4.4,75.0,50.0,419.99,basic variant price: nan,499.99,No Badge,Organic,No Coupon,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery We...",No Badge,https://m.media-amazon.com/images/I/71wTn+zoSr...,2025-08-30 19:56:00

### 1. Statistical Analysis

In [4]:
# 1. Central Tendency --- Central tendency tells us the typical or central value of a dataset.
'''
Mean
The average value of the data.
Median
The middle value when data is arranged in order.
Mode
The value that occurs most frequently.
'''

print(df["Rating"].mean())
print(df["Rating"].median())
print(df["Rating"].mode()[0])

4.407538734555054
4.5
4.6

In [6]:
# For multiple columns

df[['Rating', 'Number_of_reviews', 'Current/discounted_price']].describe()

             Rating  Number_of_reviews  Current/discounted_price
count  24278.000000       24278.000000              24278.000000
mean       4.407539         182.805503                127.415024
std        0.360563         201.540353                171.307873
min        1.000000           1.000000                  2.490000
25%        4.200000          93.000000                 35.865000
50%        4.500000         115.000000                 74.990000
75%        4.700000         182.000000                119.990000
max        5.000000         999.000000                999.990000

In [7]:
# 2. Dispersion --- Dispersion tells us how much the values are spread out

# Range --- Range shows the difference between the highest and lowest values and gives a quick idea of the overall spread.
# Range = maximum - minimum

price_range = (
    df['Current/discounted_price'].max()- df['Current/discounted_price'].min()
)

print(price_range)

997.5

In [10]:
# Variance --- Variance measures how far values are spread from the mean.

df["Current/discounted_price"].var()

29346.38731071284

In [11]:
# Standard Deviation --- Standard deviation tells us how much values typically differ from the mean.


df["Current/discounted_price"].std()

171.30787288012434

In [12]:
# 3. Percentiles --- Percentiles tell us the position of values within the dataset.

# For example, the 75th percentile means 75% of observations are at or below that value.

# They help us understand the distribution of prices, ratings, reviews, etc., and are also used to calculate IQR.

df['Current/discounted_price'].quantile([0.25, 0.50, 0.75])

0.25     35.865
0.50     74.990
0.75    119.990
Name: Current/discounted_price, dtype: float64

In [13]:
# 4. IQR --- IQR stands for Interquartile Range.
# It represents the spread of the middle 50% of the data.
# We mainly use IQR to identify outliers.

Q1 = df['Current/discounted_price'].quantile(0.25)
Q3 = df['Current/discounted_price'].quantile(0.75)

IQR = Q3 - Q1

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)

Q1: 35.865
Q3: 119.99
IQR: 84.125

In [15]:
lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

outliers = df[
    (df['Current/discounted_price'] < lower_limit) |
    (df['Current/discounted_price'] > upper_limit)
]

print(outliers)

                                                   Title  Rating  \
2      DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...     4.6
13     Seagate IronWolf 12TB NAS Internal Hard Drive ...     4.4
53     AMD RYZEN 7 9800X3D 8-Core, 16-Thread Desktop ...     4.8
74     Escort MAX 360c Radar Detector with Extra Moun...     4.4
156    Nintendo Switch™ with Neon Blue and Neon Red J...     4.7
...                                                  ...     ...
24253  Lorex Fusion 1080p HD Security Camera System w...     4.4
24260  ASUS 27” 1080P Video Conferencing Monitor (BE2...     4.4
24266  GIGABYTE Radeon RX 9070 Gaming OC 16G Graphics...     4.6
24275  GIGABYTE - AORUS FO32U2-32" QD OLED Gaming Mon...     4.3
24277  Lorex Fusion 1080p HD Security Camera System w...     4.4

       Number_of_reviews  bought_in_last_month  Current/discounted_price  \
2                  115.0                2000.0                    314.00
13                 115.0                1000.0                    249.99
53                 115.0               10000.0                    476.50
74                 115.0                  50.0                    569.95
156                115.0                 200.0                    297.77
...                  ...                   ...                       ...
24253               75.0                  50.0                    419.99
24260              115.0                 100.0                    282.04
24266               29.0                  50.0                    669.99
24275               57.0                  50.0                    899.99
24277               75.0                  50.0                    419.99

                                   Price_on_variant  Listed_price  \
2                          basic variant price: nan        349.00
13                         basic variant price: nan         66.00
53                         basic variant price: nan         66.00
74                         basic variant price: nan         66.00
156                        basic variant price: nan        339.99
...                                             ...           ...
24253                      basic variant price: nan        499.99
24260                  basic variant price: $201.02         66.00
24266                      basic variant price: nan         66.00
24275  basic variant price: Lowest price in 30 days       1099.99
24277                      basic variant price: nan        499.99

      is_best_seller is_sponsored is_couponed buy_box_availability  \
2           No Badge    Sponsored   No Coupon          Add to cart
13          No Badge    Sponsored   No Coupon          Add to cart
53       Best Seller      Organic   No Coupon          Add to cart
74          No Badge    Sponsored   No Coupon          Add to cart
156      Best Seller      Organic   No Coupon          Add to cart
...              ...          ...         ...                  ...
24253       No Badge      Organic   No Coupon          Add to cart
24260       No Badge      Organic   No Coupon          Add to cart
24266       No Badge      Organic   No Coupon          Add to cart
24275       Save 18%      Organic   No Coupon          Add to cart
24277       No Badge      Organic   No Coupon          Add to cart

                                        delivery_details  \
2                                    Delivery Mon, Sep 1
13                                   Delivery Mon, Sep 1
53                                  Delivery Fri, Aug 29
74                                   Delivery Mon, Sep 1
156                                  Delivery Mon, Sep 1
...                                                  ...
24253  FREE delivery Thu, Sep 4Or fastest delivery We...
24260  FREE delivery Thu, Sep 4Or fastest delivery Mo...
24266  FREE delivery Thu, Sep 4Or fastest delivery To...
24275  FREE delivery Thu, Sep 4Or fastest delivery We...
24277  FREE delivery Thu, Sep 4Or fastest delivery We...

      sustainability_badges  \
2                  No Badge
13                 No Badge
53                 No Badge
74                 No Badge
156                No Badge
...                     ...
24253              No Badge
24260              No Badge
24266              No Badge
24275              No Badge
24277              No Badge

                                               image_url         collected_at
2      https://m.media-amazon.com/images/I/61h78MEXoj...  2025-08-21 11:14:00
13     https://m.media-amazon.com/images/I/71ZNqv54H4...  2025-08-21 11:14:00
53     https://m.media-amazon.com/images/I/71aHvYUgX1...  2025-08-21 11:14:00
74     https://m.media-amazon.com/images/I/615VjMyXnW...  2025-08-21 11:15:00
156    https://m.media-amazon.com/images/I/71wpE+ZIeh...  2025-08-21 11:15:00
...                                                  ...                  ...
24253  https://m.media-amazon.com/images/I/71wTn+zoSr...  2025-08-30 19:55:00
24260  https://m.media-amazon.com/images/I/81bLVfMTrN...  2025-08-30 19:56:00
24266  https://m.media-amazon.com/images/I/71RLbyxkUp...  2025-08-30 19:56:00
24275  https://m.media-amazon.com/images/I/71ySPkNLkG...  2025-08-30 19:56:00
24277  https://m.media-amazon.com/images/I/71wTn+zoSr...  2025-08-30 19:56:00

[3116 rows x 15 columns]

In [16]:
# 5. Skewness --- Skewness tells us whether the distribution is symmetric or pulled toward one side.

# It helps us understand the shape of the distribution and whether extreme values may be affecting the mean.

df['Current/discounted_price'].skew()

np.float64(2.9078566753399477)

Skewness ≈ 0       → roughly symmetric
Positive skewness  → right-skewed
Negative skewness  → left-skewed

In [17]:
# 6. Kurtosis --- Kurtosis tells us about the tail behavior and extreme values of a distribution.

# It helps us understand whether the data has more or fewer extreme observations.

df["Current/discounted_price"].kurt()

np.float64(8.817421182492485)

In [19]:
# For multiple columns

df[['Rating', 'Number_of_reviews', 'Current/discounted_price']].kurt()

Rating                      6.225160
Number_of_reviews           4.571184
Current/discounted_price    8.817421
dtype: float64

In [22]:
# 7. Correlation --- Correlation measures the strength and direction of the linear relationship between two numerical variables.

# It helps us determine whether two variables tend to increase or decrease together.

df['Rating'].corr(df['Number_of_reviews'])

np.float64(0.026484038901171597)

In [23]:
df['Current/discounted_price'].corr(
    df['Number_of_reviews']
)

np.float64(-0.04674869009529445)

In [25]:
# Correlation matrix

df[['Rating',
    'Number_of_reviews',
    'Current/discounted_price']].corr()

,Rating,Number_of_reviews,Current/discounted_price
Rating,1.000000,0.026484,-0.118455
Number_of_reviews,0.026484,1.000000,-0.046749
Current/discounted_price,-0.118455,-0.046749,1.000000

+1 → Strong positive relationship
 0 → No linear relationship
-1 → Strong negative relationship

In [26]:
# 8. Covariance --- Covariance tells us whether two variables move in the same or opposite direction.

# It helps us understand the direction of the relationship between two numerical variables.

df['Rating'].cov(df['Number_of_reviews'])

np.float64(1.9245405475426467)

In [27]:
df['Current/discounted_price'].cov(
    df['Number_of_reviews']
)

np.float64(-1614.0195204181607)

Positive covariance → variables tend to move together
Negative covariance → variables tend to move oppositely
Near zero           → little linear co-movement

### 2. Hypothesis Testing
- Hypothesis testing helps us determine whether an observed difference or relationship in the sample is statistically significant or could reasonably have occurred by chance.
  
- Usually, we use a 5% significance level (α = 0.05).

p-value < 0.05
→ Reject Null Hypothesis (H₀)
→ Statistically significant result

p-value ≥ 0.05
→ Fail to Reject Null Hypothesis
→ Not statistically significant

#### 1. T-Test
- A T-test is used to compare the means of two groups.

# Step 1: Define Hypotheses

Null Hypothesis (H₀)

There is no significant difference in the average price of bestseller and non-bestseller products.

Alternate Hypothesis (H₁)

There is a significant difference in the average price of bestseller and non-bestseller products.

In [32]:
# Step 2: Python Code

from scipy.stats import ttest_ind

# Separate the two groups
best_seller = df[df['is_best_seller'] == True]['Current/discounted_price'].dropna()

non_best_seller = df[df['is_best_seller'] == False]['Current/discounted_price'].dropna()

# Independent T-Test
t_stat, p_value = ttest_ind(
    best_seller,
    non_best_seller,
    equal_var=False
)

print("T-statistic:", t_stat)
print("P-value:", p_value)

T-statistic: nan
P-value: nan

In [29]:
alpha = 0.05

if p_value < alpha:
    print("Reject Null Hypothesis")
else:
    print("Fail to Reject Null Hypothesis")

Fail to Reject Null Hypothesis

#### 2. Chi-Square Test
- Chi-Square is used when both variables are categorical.

In [33]:
from scipy.stats import chi2_contingency

# Create contingency table
table = pd.crosstab(
    df['is_best_seller'],
    df['is_sponsored']
)

print(table)

is_sponsored       Organic  Sponsored
is_best_seller
Amazon's               485        229
Best Seller            210         52
Ends in                 39          0
Limited time deal       92        157
No Badge             18831       4008
Save 10%                26          0
Save 12%                 0         23
Save 17%                27          0
Save 18%                24          0
Save 30%                59          0
Save 77%                 0          2
Save 9%                  0         14

In [37]:
chi2, p_value, dof, expected = chi2_contingency(table)

print("Chi-Square Statistic:", chi2)
print("P-value:", p_value)
print("Degrees of Freedom:", dof)

Chi-Square Statistic: 641.2889687493864
P-value: 2.0428606081643497e-130
Degrees of Freedom: 11

In [38]:
alpha = 0.05

if p_value < alpha:
    print("Reject Null Hypothesis")
else:
    print("Fail to Reject Null Hypothesis")

Reject Null Hypothesis

#### 3. ANOVA
- ANOVA = Analysis of Variance.
- It is used to compare the means of three or more groups.

In [39]:
df['rating_group'] = pd.cut(
    df['Rating'],
    bins=[0, 3, 4, 5],
    labels=['Low', 'Medium', 'High']
)

In [40]:
from scipy.stats import f_oneway

low = df[
    df['rating_group'] == 'Low']['Current/discounted_price'].dropna()

medium = df[
    df['rating_group'] == 'Medium']['Current/discounted_price'].dropna()

high = df[
    df['rating_group'] == 'High']['Current/discounted_price'].dropna()

f_stat, p_value = f_oneway(
    low,
    medium,
    high
)

print("F-statistic:", f_stat)
print("P-value:", p_value)

F-statistic: 611.2450357153017
P-value: 1.0178536058349366e-259

In [41]:
alpha = 0.05

if p_value < alpha:
    print("Reject Null Hypothesis")
else:
    print("Fail to Reject Null Hypothesis")

Reject Null Hypothesis

#### 4. Correlation Significance Test

In [42]:
from scipy.stats import pearsonr

r, p_value = pearsonr(
    df['Rating'].dropna(),
    df['Number_of_reviews'].dropna()
)

print("Correlation:", r)
print("P-value:", p_value)

Correlation: 0.026484038901171764
P-value: 3.673743545659829e-05

## 3. Confidence Interval Analysis
- A Confidence Interval (CI) gives us a range of values that is likely to contain the true population parameter, based on our sample.

In [44]:
# 1. Confidence Interval for Average Rating

import numpy as np
from scipy import stats

In [45]:
rating = df["Rating"].dropna()

In [46]:
mean_rating = rating.mean()

confidence_level = 0.95
alpha = 1 - confidence_level

confidence_interval = stats.t.interval(
    confidence_level,
    df=len(rating)-1,
    loc=mean_rating,
    scale=stats.sem(rating)
)

print("Mean Rating:", mean_rating)
print("95% Confidence Interval:", confidence_interval)

Mean Rating: 4.407538734555054
95% Confidence Interval: (np.float64(4.403003036612144), np.float64(4.412074432497963))

In [47]:
# 2. Confidence Interval for Product Price

price = df['Current/discounted_price'].dropna()

mean_price = price.mean()

confidence_interval = stats.t.interval(
    0.95,
    df=len(price)-1,
    loc=mean_price,
    scale=stats.sem(price)
)

print("Mean Price:", mean_price)
print("95% Confidence Interval:", confidence_interval)

Mean Price: 127.4150238899415
95% Confidence Interval: (np.float64(125.26005694508433), np.float64(129.56999083479866))

In [48]:
# Confidence Interval for Number of Reviews

reviews = df['Number_of_reviews'].dropna()

mean_reviews = reviews.mean()

confidence_interval = stats.t.interval(
    0.95,
    df=len(reviews)-1,
    loc=mean_reviews,
    scale=stats.sem(reviews)
)

print("Mean Reviews:", mean_reviews)
print("95% Confidence Interval:", confidence_interval)

Mean Reviews: 182.80550292445835
95% Confidence Interval: (np.float64(180.2702265791618), np.float64(185.3407792697549))

In [49]:
# Create a Reusable Function

def confidence_interval(data, confidence=0.95):
    
    data = data.dropna()
    
    mean = data.mean()
    
    ci = stats.t.interval(
        confidence,
        df=len(data)-1,
        loc=mean,
        scale=stats.sem(data)
    )
    
    return mean, ci

In [50]:
mean_rating, ci_rating = confidence_interval(df['Rating'])

print("Mean Rating:", mean_rating)
print("95% CI:", ci_rating)

Mean Rating: 4.407538734555054
95% CI: (np.float64(4.403003036612144), np.float64(4.412074432497963))

In [51]:
mean_price, ci_price = confidence_interval(
    df['Current/discounted_price']
)

print("Mean Price:", mean_price)
print("95% CI:", ci_price)

Mean Price: 127.4150238899415
95% CI: (np.float64(125.26005694508433), np.float64(129.56999083479866))

### 4. Feature Engineering
- Feature Engineering means creating new meaningful columns from existing columns to make the data more useful for analysis and business decision-making.

In [52]:
# 1. Discount Percentage

df['Discount_Percentage'] = (
    (df['Listed_price'] - df['Current/discounted_price'])
    / df['Listed_price']
) * 100

In [54]:
df[['Listed_price','Current/discounted_price','Discount_Percentage']].head()

   Listed_price  Current/discounted_price  Discount_Percentage
0        159.00                     89.68            43.597484
1         15.99                      9.99            37.523452
2        349.00                    314.00            10.028653
3         66.00                     74.99           -13.621212
4         66.00                     74.99           -13.621212

In [55]:
# 2. Discount Category

df['Discount_Category'] = pd.cut(df['Discount_Percentage'],bins=[-1, 10, 30, 50, 100],
    labels=[
        'Low Discount',
        'Medium Discount',
        'High Discount',
        'Very High Discount'
    ]
)

In [56]:
df['Discount_Category'].value_counts()

Discount_Category
Medium Discount       4669
Very High Discount    3131
High Discount         2129
Low Discount          1685
Name: count, dtype: int64

In [57]:
# 3. Rating Category

df['Rating_Category'] = pd.cut(
    df['Rating'],
    bins=[0, 3, 4, 5],
    labels=[
        'Low Rating',
        'Medium Rating',
        'High Rating'
    ]
)

In [58]:
df['Rating_Category'].value_counts()

Rating_Category
High Rating      20942
Medium Rating     3161
Low Rating         175
Name: count, dtype: int64

In [59]:
# 4. Review Engagement Category

df['Review_Engagement'] = pd.cut(
    df['Number_of_reviews'],
    bins=[-1, 100, 1000, 10000, float('inf')],
    labels=[
        'Low',
        'Medium',
        'High',
        'Very High'
    ]
)

In [60]:
df['Review_Engagement'].value_counts()

Review_Engagement
Medium       17955
Low           6323
High             0
Very High        0
Name: count, dtype: int64

In [67]:
# 5. Price Category

df['Price_Category'] = pd.cut(
    df['Current/discounted_price'],
    bins=[-1, 20, 50, 100, float('inf')],
    labels=[
        'Budget',
        'Mid-Range',
        'Premium',
        'High-Premium'
    ]
)

In [68]:
# 6. Promotion Flag

df['Promotion_Flag'] = (
    (df['is_couponed'] == True) |
    (df['is_sponsored'] == True)
)

In [72]:
# 7. Bestseller + High Rating Feature

df['High_Rated_Bestseller'] = (
    (df['Rating'] >= 4) &
    (df['is_best_seller'] == True)
)

In [74]:
# Price per Review

df['Price_per_Review'] = (
    df['Current/discounted_price']
    / df['Number_of_reviews'].replace(0, np.nan)
)

In [76]:
# Product Performance Segment

df['Performance_Segment'] = np.where(
    (df['Rating'] >= 4) &
    (df['Number_of_reviews'] >= 1000),
    'Strong Performance',
    'Other'
)

### 5. Feature Evaluation
- Feature Evaluation means comparing the dataset before and after feature engineering to determine whether the new features make the analysis more meaningful and easier to interpret.

- We use it to check whether engineered features help us get better segmentation, clearer pricing insights, better product-performance analysis, and deeper marketplace understanding.

In [78]:
before_features = [
    'Rating',
    'Current/discounted_price',
    'Number_of_reviews',
    'is_best_seller',
    'is_sponsored',
    'is_couponed'
]

after_features = [
    'Discount_Percentage',
    'Discount_Category',
    'Rating_Category',
    'Price_Category',
    'Promotion_Flag',
    'High_Rated_Bestseller'
]

print("Before Feature Engineering:")
print(before_features)

print("\nAfter Feature Engineering:")
print(after_features)

Before Feature Engineering:
['Rating', 'Current/discounted_price', 'Number_of_reviews', 'is_best_seller', 'is_sponsored', 'is_couponed']

After Feature Engineering:
['Discount_Percentage', 'Discount_Category', 'Rating_Category', 'Price_Category', 'Promotion_Flag', 'High_Rated_Bestseller']

In [83]:
# Before
df[['Listed_price','Current/discounted_price']].head()

   Listed_price  Current/discounted_price
0        159.00                     89.68
1         15.99                      9.99
2        349.00                    314.00
3         66.00                     74.99
4         66.00                     74.99

In [84]:
# After

df[
    ['Listed_price',
     'Current/discounted_price',
     'Discount_Percentage',
     'Discount_Category']
].head()

,Listed_price,Current/discounted_price,Discount_Percentage,Discount_Category
0,159.00,89.68,43.597484,High Discount
1,15.99,9.99,37.523452,High Discount
2,349.00,314.00,10.028653,Medium Discount
3,66.00,74.99,-13.621212,NaN
4,66.00,74.99,-13.621212,NaN

In [88]:
# Before Feature Engineering 

df[
    ['Rating',
     'Number_of_reviews',
     'is_best_seller']
].head()

   Rating  Number_of_reviews is_best_seller
0     4.6              375.0       No Badge
1     4.3              115.0       No Badge
2     4.6              115.0       No Badge
3     4.6              115.0    Best Seller
4     4.8              115.0       No Badge

In [89]:
# After 

df[
    ['Rating',
     'Number_of_reviews',
     'is_best_seller']
].head()

   Rating  Number_of_reviews is_best_seller
0     4.6              375.0       No Badge
1     4.3              115.0       No Badge
2     4.6              115.0       No Badge
3     4.6              115.0    Best Seller
4     4.8              115.0       No Badge

## 6. Final Business Recommendations

1. Product Positioning

Recommendation:
Group products into clear segments based on rating, price, discount, and purchase activity.

Evidence:
The engineered features such as Rating_Category, Price_Category, and Purchase_Category make it easier to identify products with different performance levels.

Business Action:

Highlight highly rated products.
Create separate positioning for budget, mid-range, and premium products.
Give more attention to products with high ratings and strong purchase activity.

Expected Benefit:
Customers can find suitable products more easily, and the business can target different customer segments.

2. Pricing Strategy

Recommendation:
Use discount percentage and price categories to evaluate pricing performance instead of looking only at the listed price.

Evidence:
The Discount_Percentage feature shows how much discount each product receives, while Price_Category helps compare different price levels.

Business Action:

Identify products where discounts are frequently used.
Compare purchase activity across different discount levels.
Avoid giving unnecessarily high discounts when lower discounts perform similarly.

Expected Benefit:
The business can make pricing decisions based on customer response rather than using the same discount strategy for every product.

3. Promotional Strategy

Recommendation:
Evaluate coupons and sponsored promotions separately and together to understand their relationship with product performance.

Evidence:
The dataset contains is_couponed and is_sponsored, and the engineered Promotion_Flag and Promotion_Count make promotional activity easier to analyze. The Chi-square test also showed a statistically significant association between the categorical variables tested (χ² = 641.29, p < 0.05).

Business Action:

Compare purchase activity for promoted and non-promoted products.
Identify whether coupons or sponsored placement are more commonly associated with high-performing products.
Use promotions selectively for products that need additional visibility.

Expected Benefit:
Marketing spending can be used more efficiently.

Important: Association does not prove that promotion causes higher sales. Other factors may also influence performance.

4. Product Visibility

Recommendation:
Use sponsored placement and product performance indicators to improve product visibility.

Evidence:
The dataset contains is_sponsored, is_best_seller, ratings, reviews, and purchase indicators. These features allow the business to identify products that have visibility but different levels of customer response.

Business Action:

Monitor sponsored products separately.
Identify products receiving visibility but showing weak customer engagement.
Improve product information, pricing, or offers before increasing promotion.

Expected Benefit:
The business can focus visibility efforts on products with potential for better customer response.

5. Customer Engagement

Recommendation:
Use ratings, review counts, and monthly purchase indicators to understand customer engagement.

Evidence:
The Monthly_Purchases feature converts text such as "300+ bought in past month" into a numerical feature, while Rating_Category and review information allow products to be compared more easily.

Business Action:

Identify products with high purchase activity.
Encourage customers to provide reviews.
Monitor products with good ratings but low purchase activity for possible pricing or visibility issues.

Expected Benefit:
Better understanding of customer interest can help improve product presentation and engagement.

6. Marketplace Performance

Recommendation:
Monitor marketplace performance using a combination of price, discount, rating, purchase activity, bestseller status, and promotion rather than relying on a single metric.

Evidence:
Feature engineering created combined indicators such as High_Rated_Bestseller, Promotion_Count, Price_Category, and Purchase_Category. These provide more meaningful product-level comparisons than individual raw columns.

Business Action:
Create regular product-performance reports containing:

Rating
Number of reviews
Monthly purchases
Price
Discount percentage
Bestseller status
Sponsored status
Coupon status

Expected Benefit:
The business can identify strong products, products requiring improvement, and areas where pricing or promotional strategies need adjustment.